// 通用角色目录；持续状态与一次性表达分开，业务映射放在适配层。
export const BOT_DEFINITIONS = {
  idle: {
    id: "idle",
    name: "待命",
    desc: "方块微微换重心，眼神偶尔游移，始终留在原位。",
    eyes: "柔和双眼；偶尔侧看",
    rhythm: "8 秒长节奏",
    trigger: "没有活跃工作",
    signature: "重心微移",
    period: 8,
    duration: 0,
    ribbon: "none",
    group: "state",
  },
  listening: {
    id: "listening",
    name: "倾听",
    desc: "上半身向输入方向探出，底部留在原位，像认真侧耳。",
    eyes: "双眼张开，注视一侧",
    rhythm: "3.8 秒；前倾后停留",
    trigger: "用户输入或真实的监听状态",
    signature: "前倾探身",
    period: 3.8,
    duration: 0,
    ribbon: "none",
    group: "state",
  },
  connecting: {
    id: "connecting",
    name: "建立连接",
    desc: "两侧向内收，随后展开；第二拍比第一拍更接近完整方形。",
    eyes: "目光从两侧回到中央",
    rhythm: "2.8 秒；收合—展开",
    trigger: "连接正在建立",
    signature: "横向收合",
    period: 2.8,
    duration: 0,
    ribbon: "join",
    group: "state",
  },
  receiving: {
    id: "receiving",
    name: "接收",
    desc: "方块接住一股向下的动量，轻压后回弹，重心随之落下。",
    eyes: "视线从上落到中央",
    rhythm: "2.8 秒；承接—回弹",
    trigger: "正在接收输入、数据或结果",
    signature: "向下承接",
    period: 2.8,
    duration: 0,
    ribbon: "inward",
    group: "state",
  },
  sending: {
    id: "sending",
    name: "发送",
    desc: "先压低，再向上伸展，把动量送出去；身体随后回收。",
    eyes: "视线先抬起，动作后跟上",
    rhythm: "2.6 秒；蓄力—推出",
    trigger: "正在发送数据或消息",
    signature: "向上推出",
    period: 2.6,
    duration: 0,
    ribbon: "outward",
    group: "state",
  },
  thinking: {
    id: "thinking",
    name: "思考",
    desc: "身体慢慢扭向一侧，再悬停转回；彩线顺着转身绕过腰部。",
    eyes: "一眼收窄，目光略向上",
    rhythm: "5.2 秒；慢转—悬停—回转",
    trigger: "显式思考或推理阶段",
    signature: "悬停扭转",
    period: 5.2,
    duration: 0,
    ribbon: "orbit",
    group: "state",
  },
  planning: {
    id: "planning",
    name: "规划",
    desc: "方块依次倾向左、中、右三个稳定落点，最后把自己摆正。",
    eyes: "视线先到下一个落点",
    rhythm: "3.6 秒；三段落点",
    trigger: "显式计划与安排阶段",
    signature: "三段落点",
    period: 3.6,
    duration: 0,
    ribbon: "none",
    group: "state",
  },
  searching: {
    id: "searching",
    name: "搜索",
    desc: "身体侧转探出，停一下，再去另一侧；横向行程清晰可见。",
    eyes: "宽眼寻找，眼神先于转身",
    rhythm: "3.2 秒；探左—停—探右",
    trigger: "正在寻找信息或目标",
    signature: "左右探寻",
    period: 3.2,
    duration: 0,
    ribbon: "none",
    group: "state",
  },
  reading: {
    id: "reading",
    name: "阅读",
    desc: "方块很轻地顺着行进方向倾斜；行尾复位，再小幅下沉。",
    eyes: "从左至右，回扫换行",
    rhythm: "3 秒；横扫—回扫—换行",
    trigger: "顺序消费文本、图像或内容",
    signature: "逐行下沉",
    period: 3,
    duration: 0,
    ribbon: "none",
    group: "state",
  },
  working: {
    id: "working",
    name: "执行",
    desc: "底部撑住，身体压缩向前推进，再弹回准备下一拍。",
    eyes: "双眼聚焦，注视前下方",
    rhythm: "2.2 秒；压缩—推进—回弹",
    trigger: "工具或计算正在执行",
    signature: "弹性推进",
    period: 2.2,
    duration: 0,
    ribbon: "drive",
    group: "state",
  },
  generating: {
    id: "generating",
    name: "生成",
    desc: "身体左右交替舒展，像有节奏地织出连续内容。",
    eyes: "双眼随左右节奏交替聚焦",
    rhythm: "2.6 秒；左展—右展—停顿",
    trigger: "正在生成内容或持续输出",
    signature: "左右舒展",
    period: 2.6,
    duration: 0,
    ribbon: "weave",
    group: "state",
  },
  verifying: {
    id: "verifying",
    name: "检查",
    desc: "方块先横向收紧，再纵向拉直，最后严格回到中轴。",
    eyes: "双眼同时眯起，再恢复平齐",
    rhythm: "3 秒；收紧—对齐—停顿",
    trigger: "正在验证、评估或复核",
    signature: "收紧对齐",
    period: 3,
    duration: 0,
    ribbon: "none",
    group: "state",
  },
  coordinating: {
    id: "coordinating",
    name: "协同",
    desc: "上、下半身形成轻微反向扭转，随后换边，带动两条交错轨迹。",
    eyes: "轮流关注两个方向",
    rhythm: "3.8 秒；换边扭转",
    trigger: "正在协调多个活跃工作单元",
    signature: "交替扭身",
    period: 3.8,
    duration: 0,
    ribbon: "cross",
    group: "state",
  },
  waiting: {
    id: "waiting",
    name: "等待",
    desc: "方块向一侧轻靠，双眼放松；等候时留在这个重心。",
    eyes: "半开双眼，安静侧望",
    rhythm: "6 秒；只轻移一次眼神",
    trigger: "已知外部依赖正在等待",
    signature: "侧靠停留",
    period: 6,
    duration: 0,
    ribbon: "none",
    group: "state",
  },
  "awaiting-input": {
    id: "awaiting-input",
    name: "等待回应",
    desc: "先直起身，再向前探一点；双眼看向用户，保持这个姿态。",
    eyes: "正面睁眼，注视用户",
    rhythm: "360 毫秒进入后保持",
    trigger: "需要用户输入、选择或确认",
    signature: "挺身注视",
    period: 0,
    duration: 0,
    ribbon: "none",
    group: "state",
  },
  blocked: {
    id: "blocked",
    name: "受阻",
    desc: "方块向右尝试推进，仿佛受到阻力，侧面被压住后停下。",
    eyes: "一眼收紧，一眼留意阻力",
    rhythm: "480 毫秒进入后保持",
    trigger: "确定的障碍使工作无法继续",
    signature: "侧向受压",
    period: 0,
    duration: 0,
    ribbon: "none",
    group: "state",
  },
  retrying: {
    id: "retrying",
    name: "重试",
    desc: "先略向后撤，把身体重新拧紧，再沿原方向试着起步。",
    eyes: "回望一下，再重新聚焦",
    rhythm: "3.2 秒；撤回—蓄力—再试",
    trigger: "真实重试已开始",
    signature: "撤回再起",
    period: 3.2,
    duration: 0,
    ribbon: "rewind",
    group: "state",
  },
  settling: {
    id: "settling",
    name: "收尾",
    desc: "大幅动作逐步收小，身体从轻扭转归正；彩带顺势收拢。",
    eyes: "眼神回中，逐渐放松",
    rhythm: "3.4 秒后安定；仍可保持此态",
    trigger: "工作进入最终整理阶段",
    signature: "归拢安定",
    period: 0,
    duration: 0,
    ribbon: "settle",
    group: "state",
  },
  completed: {
    id: "completed",
    name: "完成",
    desc: "向上舒展一次，双眼弯起，落在高而端正的姿态。",
    eyes: "对称的满意眼形",
    rhythm: "600 毫秒进入后保持",
    trigger: "工作已经成功结束",
    signature: "舒展站稳",
    period: 0,
    duration: 0,
    ribbon: "none",
    group: "state",
  },
  partial: {
    id: "partial",
    name: "部分完成",
    desc: "身体一侧已经舒展，另一侧仍略收着，保留未完全落定的形状。",
    eyes: "一眼柔和，一眼保持注意",
    rhythm: "420 毫秒进入后保持",
    trigger: "部分结果就绪，仍有未完成部分",
    signature: "非对称舒展",
    period: 0,
    duration: 0,
    ribbon: "none",
    group: "state",
  },
  failed: {
    id: "failed",
    name: "失败",
    desc: "力气卸下来，上缘略低、底部变宽；身体稳住，不再试着推进。",
    eyes: "双眼稍低，仍然清醒",
    rhythm: "480 毫秒卸力后保持",
    trigger: "本次工作已失败并结束",
    signature: "向下卸力",
    period: 0,
    duration: 0,
    ribbon: "none",
    group: "state",
  },
  cancelled: {
    id: "cancelled",
    name: "已停止",
    desc: "向前的动量被收回，身体短暂后坐，再回到较低的稳定姿态。",
    eyes: "中性横眼，视线回中",
    rhythm: "450 毫秒刹住后保持",
    trigger: "明确的停止或取消已经确认",
    signature: "回收刹停",
    period: 0,
    duration: 0,
    ribbon: "none",
    group: "state",
  },
  paused: {
    id: "paused",
    name: "暂停",
    desc: "保持一半转身，身体收窄，像把动作暂时留在空中。",
    eyes: "双眼半开，方向仍保留",
    rhythm: "240 毫秒收束后保持",
    trigger: "工作明确暂停，可继续",
    signature: "半转悬停",
    period: 0,
    duration: 0,
    ribbon: "none",
    group: "state",
  },
  sleeping: {
    id: "sleeping",
    name: "休息",
    desc: "身体柔软地压低，靠向一侧，眼睛合成两条弧线。",
    eyes: "完全闭眼",
    rhythm: "600 毫秒进入后保持",
    trigger: "明确休息或非工作展示",
    signature: "低伏合眼",
    period: 0,
    duration: 0,
    ribbon: "none",
    group: "state",
  },
  appear: {
    id: "appear",
    name: "出现",
    desc: "从紧凑的小方块展开，双眼随身体睁开，落定。",
    eyes: "从合眼到睁眼",
    rhythm: "600 毫秒",
    trigger: "新角色首次出现",
    signature: "展开成形",
    period: 0,
    duration: 0.6,
    ribbon: "none",
    group: "cue",
  },
  acknowledge: {
    id: "acknowledge",
    name: "收到",
    desc: "眼睛先回应，方块前倾并点一下头，回正。",
    eyes: "正面注意",
    rhythm: "480 毫秒",
    trigger: "输入被确认接收",
    signature: "短促点头",
    period: 0,
    duration: 0.48,
    ribbon: "none",
    group: "cue",
  },
  dispatch: {
    id: "dispatch",
    name: "派发",
    desc: "方块向右拧身再回弹，彩线随这个甩动向外舒展。",
    eyes: "先看派发方向",
    rhythm: "720 毫秒",
    trigger: "一次真实工作派发",
    signature: "拧身甩出",
    period: 0,
    duration: 0.72,
    ribbon: "outward",
    group: "cue",
  },
  "receive-result": {
    id: "receive-result",
    name: "接住",
    desc: "侧转迎向来处，身体压下接住，再舒展回中。",
    eyes: "迎向来处，再回正",
    rhythm: "680 毫秒",
    trigger: "一个结果返回",
    signature: "侧身承接",
    period: 0,
    duration: 0.68,
    ribbon: "inward",
    group: "cue",
  },
  milestone: {
    id: "milestone",
    name: "有进展",
    desc: "一侧肩角轻抬，身体转出短弧，再继续工作。",
    eyes: "短暂满意",
    rhythm: "680 毫秒",
    trigger: "有意义的阶段进展",
    signature: "轻抬一角",
    period: 0,
    duration: 0.68,
    ribbon: "arc",
    group: "cue",
  },
  notify: {
    id: "notify",
    name: "注意到了",
    desc: "方块短促挺高，双眼放大，然后带一点弹性落回。",
    eyes: "双眼同时张开",
    rhythm: "640 毫秒",
    trigger: "明确的新信息提醒",
    signature: "挺高回落",
    period: 0,
    duration: 0.64,
    ribbon: "none",
    group: "cue",
  },
  recover: {
    id: "recover",
    name: "恢复",
    desc: "受压的身体释放开来，先宽后高，沿顺滑轨迹回正。",
    eyes: "重新聚焦",
    rhythm: "820 毫秒",
    trigger: "收到真实的恢复证据",
    signature: "解压复位",
    period: 0,
    duration: 0.82,
    ribbon: "join",
    group: "cue",
  },
  celebrate: {
    id: "celebrate",
    name: "庆祝",
    desc: "预压、跃起、转身，三条彩带绕着身形展开，再收进满意的落定。",
    eyes: "转身时收眼，落定时弯眼",
    rhythm: "1400 毫秒",
    trigger: "被见证的一次成功",
    signature: "跃起回旋",
    period: 0,
    duration: 1.4,
    ribbon: "celebrate",
    group: "cue",
  },
  blink: {
    id: "blink",
    name: "眨眼",
    desc: "快速合拢，短停，再自然睁开。",
    eyes: "同步开合",
    rhythm: "220 毫秒",
    trigger: "自然眨眼",
    signature: "自然开合",
    period: 0,
    duration: 0.22,
    ribbon: "none",
    group: "micro",
  },
  glance: {
    id: "glance",
    name: "看一眼",
    desc: "眼睛先动，头部轻跟随，再回正。",
    eyes: "侧看回正",
    rhythm: "720 毫秒",
    trigger: "局部注意力变化",
    signature: "视线先行",
    period: 0,
    duration: 0.72,
    ribbon: "none",
    group: "micro",
  },
  curious: {
    id: "curious",
    name: "好奇",
    desc: "一边肩角抬起，身体轻歪，双眼一大一小。",
    eyes: "不对称张眼",
    rhythm: "1000 毫秒",
    trigger: "待命时的稀疏表达",
    signature: "歪身打量",
    period: 0,
    duration: 1,
    ribbon: "none",
    group: "micro",
  },
  content: {
    id: "content",
    name: "会心",
    desc: "身体略向上松开，双眼柔和弯起，回落。",
    eyes: "轻微笑眼",
    rhythm: "900 毫秒",
    trigger: "明确的积极回应",
    signature: "轻松舒展",
    period: 0,
    duration: 0.9,
    ribbon: "none",
    group: "micro",
  },
} as const;

export type BotState = keyof typeof BOT_DEFINITIONS;
export type BotCue = {
  [K in BotState]: (typeof BOT_DEFINITIONS)[K]["group"] extends "state"
    ? never
    : K;
}[BotState];
export type BotPersistentState = Exclude<BotState, BotCue>;
export type RibbonKind = (typeof BOT_DEFINITIONS)[BotState]["ribbon"];
export const ALL_STATES = Object.keys(BOT_DEFINITIONS) as BotState[];
export const STATE_GROUPS = [
  {
    label: "工作状态",
    states: ALL_STATES.filter((s) => BOT_DEFINITIONS[s].group === "state"),
  },
  {
    label: "事件动作",
    states: ALL_STATES.filter((s) => BOT_DEFINITIONS[s].group === "cue"),
  },
  {
    label: "微表情",
    states: ALL_STATES.filter((s) => BOT_DEFINITIONS[s].group === "micro"),
  },
];
export function isBotState(value: unknown): value is BotState {
  return typeof value === "string" && Object.hasOwn(BOT_DEFINITIONS, value);
}
export const URGENT_STATES = new Set<BotState>([
  "awaiting-input",
  "blocked",
  "failed",
  "partial",
  "cancelled",
  "paused",
  "completed",
]);
export function isWorkingState(state: BotState): boolean {
  return (
    BOT_DEFINITIONS[state].group === "state" &&
    ![
      "idle",
      "sleeping",
      "completed",
      "partial",
      "failed",
      "cancelled",
      "paused",
      "blocked",
      "awaiting-input",
    ].includes(state)
  );
}
